#https://www.shadertoy.com/view/Xds3Rr

[sound]
audio = "../share/shadertoy_electronebulae.mp3"

[[pass]]
clear     = [0.0, 0.0, 0.0, 1.0]
draw      = {mode = "triangles", count = 1}
vertex    = "../share/fullscreen_triangle.glsl"
fragment  = "./image.glsl"
iChannel0 = {resource="sound", filter="linear", wrap="clamp"}
